### ISSUE TITLE
Not support Orin NX

### ISSUE THREAD

**Issue by Zack0617** [NVIDIA-AI-IOT/TAO-PTM-Jetson-Benchmarks#1]
When run the benchmark for  PeopleNet, got the issue:

~/TAO-PTM-Jetson-Benchmarks$ sudo python3 benchmark.py --model_name peoplenet --csv_file_path benchmark_csv/orin_ptm.csv --model_dir $HOME/TAO-PTM-Jetson-Benchmarks/models/
Please close all other applications and Press Enter to continue...
Setting Jetson orin in max performance mode
Jetson clocks are Set
Jetson clocks with Fan set
------------Executing peoplenet------------

readWriteData: GPU:6.9771214007782065, DLA0:0, DLA1:0
Error in Build, Please check the log in: /home/zack/TAO-PTM-Jetson-Benchmarks/models/
Error in Build, Please check the log in: /home/zack/TAO-PTM-Jetson-Benchmarks/models/
We recommend to run benchmarking in headless mode
--------------------------

Model Name: peoplenet 
FPS:0.00 

--------------------------

**Comment by AsawareeBhide** [comment]
Hi! Could you please attach the log file here?

**Comment by Zack0617** [comment]
@AsawareeBhide Thank you, it resolved by changing the DLA engine file name from "peoplenet_dla_0.engine" to "peoplenet_dla_bs4.engine"
